# Gradient Boost Classification Algorithm

In [1]:
# import libraries
import numpy as np
import pandas as pd

In [2]:
#ignore warnings
import warnings
warnings.filterwarnings("ignore")

# show all rows and all columns
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [3]:
# load dataset
from sklearn.datasets import load_breast_cancer
data =  load_breast_cancer()

In [4]:
data.data          # in dictionary format

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [6]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [8]:
# create dataframe
df = pd.DataFrame(np.c_[data.data,data.target],columns = [list(data.feature_names)+['target']])
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension radius error texture error perimeter error  \
0                0.07871       1.0950        0.9053           8.589   
1                0.05667       0.5435        0.7339           3.398   
2                0.05999       0.7456        0.7869           4.585   
3                0.09744       0.4956        1.1560           3.445   
4                0.05883       0.7572        0.7813           5.438   

  area error smoothness error compactness error concavity error  \
0     153.40         0.006399           0.04904         0.05373   
1      74.08         0.005225           0.01308         0.01860   
2      94.03         0.006150           0.04006         0.03832   
3      27.23         0.009110           0.07458         0.05661   
4      94.44         0.011490           0.02461         0.05688   

  concave points error symmetry error fractal dimension error worst radius  \
0              0.01587        0.03003                0.006193        25.38   
1              0.01340        0.01389                0.003532        24.99   
2              0.02058        0.02250                0.004571        23.57   
3              0.01867        0.05963                0.009208        14.91   
4              0.01885        0.01756                0.005115        22.54   

  worst texture worst perimeter worst area worst smoothness worst compactness  \
0         17.33          184.60     2019.0           0.1622            0.6656   
1         23.41          158.80     1956.0           0.1238            0.1866   
2         25.53          152.50     1709.0           0.1444            0.4245   
3         26.50           98.87      567.7           0.2098            0.8663   
4         16.67          152.20     1575.0           0.1374            0.2050   

  worst concavity worst concave points worst symmetry worst fractal dimension  \
0          0.7119               0.2654         0.4601                 0.11890   
1          0.2416               0.1860         0.2750                 0.08902   
2          0.4504               0.2430         0.3613                 0.08758   
3          0.6869               0.2575         0.6638                 0.17300   
4          0.4000               0.1625         0.2364                 0.07678   

  target  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [9]:
df.shape

(569, 31)

# Split Data

In [10]:
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [11]:
X.shape,y.shape

((569, 30), (569,))

In [12]:
# now we will split data into train and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=51)
print("Shape of X_train = ", X_train.shape)
print("Shape of y_train = ", y_train.shape)
print("Shape of X_test = ", X_test.shape)
print("Shape of y_test = ", y_test.shape)

Shape of X_train =  (455, 30)
Shape of y_train =  (455,)
Shape of X_test =  (114, 30)
Shape of y_test =  (114,)


# Train Gradient Boost Classification Model

In [13]:
from sklearn.ensemble import GradientBoostingClassifier

In [14]:
classifier = GradientBoostingClassifier()
classifier.fit(X_train,y_train)

GradientBoostingClassifier()

In [15]:
classifier.score(X_test,y_test)

0.9385964912280702

# Predict Cancer

In [16]:
patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [17]:
patient1 = np.array([patient1])       # convert it into two dimension numpy array
patient1

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [18]:
pred = classifier.predict(patient1)
pred

array([0.])

In [19]:
if pred[0] ==0 :
    print('Patient has cancer (malignant tumor)')
else :
    print('Patient has no cancer (malignant benign)')

Patient has cancer (malignant tumor)
