# Business Problem - Predict the Price of Banglore House
Using Support Vector Regression - Superviesd Machine Learning Algorithm

In [1]:
import pandas as pd

In [2]:
#ignore warnings
import warnings
warnings.filterwarnings("ignore")

# show all rows and all columns
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [3]:
df = pd.read_csv(r"C:\Users\user\Pictures\PYTHON_PANDAS\bangalore_house_prediction.csv")   # this is already cleaned dataset
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Raja Rajeshwari Nagar  location_Haralur Road  \
0                               0                      0   
1                               0                      0   
2                               0                      0   
3                               0                      0   
4                               0                      0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_7th Phase JP Nagar  location_Yelahanka  location_Kanakpura Road  \
0                            0                   0                        0   
1                            0                   0                        0   
2                            0                   0                        0   
3                            0                   0                        0   
4                            0                   0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Kasavanhalli  location_Bellandur  location_Begur Road  \
0                      0                   0                    0   
1               

# Split Data

In [4]:
X = df.drop('price',axis=1)
y = df['price']   # price is a dependent variable

print("Shape of X = ", X.shape)
print("Shape of y = ", y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [5]:
# now we will split data into train and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=51)
print("Shape of X_train = ", X_train.shape)
print("Shape of y_train = ", y_train.shape)
print("Shape of X_test = ", X_test.shape)
print("Shape of y_test = ", y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


# Feature Scaling

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

# Support Vector Regression - ML Model Training

In [8]:
from sklearn.svm import SVR

In [10]:
svr_rbf = SVR(kernel="rbf")
svr_rbf.fit(X_train,y_train)
svr_rbf.score(X_test,y_test)

0.2063803584082815

In [11]:
svr_linear = SVR(kernel="linear")
svr_linear.fit(X_train,y_train)
svr_linear.score(X_test,y_test)

0.7962725308517551

In [13]:
svr_poly = SVR(kernel="poly",degree=2)
svr_poly.fit(X_train,y_train)
svr_poly.score(X_test,y_test)

0.18266215211874626

# Predict the Value of Home and Test

In [14]:
X_test[0]

array([ 0.71301986,  0.0112734 ,  0.30202307,  0.65677518, -0.48064341,
       -1.7385623 ,  2.11587407, -0.25430867,  0.51007548, -0.18373025,
       -0.16389438, -0.1473229 , -0.13023539, -0.12812824, -0.12598816,
       -0.12454231, -0.12953656, -0.12381344, -0.12010681, -0.11551113,
       -0.10992018, -0.10909925, -0.10660036, -0.11234866, -0.09315135,
       -0.08618799, -0.08923672, -0.09023078, -0.08721571, -0.09023078,
       -0.08721571, -0.08195215, -0.08195215, -0.07633675, -0.0751646 ,
       -0.08085949, -0.0739743 , -0.07975227, -0.07153563, -0.0751646 ,
       -0.0677166 , -0.08085949, -0.07153563, -0.07862985, -0.0751646 ,
       -0.07862985, -0.06504853, -0.0751646 , -0.06901264, -0.0751646 ,
       -0.06901264, -0.07028523, -0.07276497, -0.07028523, -0.06367332,
       -0.06226825, -0.06226825, -0.06639573, -0.06504853, -0.05935999,
       -0.06083125, -0.06639573, -0.06639573, -0.06226825, -0.06367332,
       -0.05935999, -0.06639573, -0.06367332, -0.06226825, -0.06

In [17]:
svr_linear.predict([X_test[0]])

array([86.53673464])

In [18]:
y_pred = svr_linear.predict(X_test)
y_pred

array([ 86.53673464,  33.70390806, 122.48356838, ...,  26.23978753,
        64.52634655, 176.17532793])

In [19]:
y_test

2435      80.000
3113      40.000
426      120.000
1124      79.000
1161      45.000
1724      39.000
1110      53.000
3591      78.000
1978     101.000
4383      62.000
4602     105.000
3536     246.000
820      198.000
4500     233.000
5550     145.000
1273      48.000
1905      86.000
5007      94.000
4447     160.000
6589      54.000
1349      69.000
2803      48.000
3184      57.000
7031      75.000
5067     175.000
2267     400.000
7037      25.000
614       65.000
6137     153.000
5824     175.000
5332      56.000
843       51.980
1471      85.000
6999     260.000
3369     111.000
6405      47.000
2812      60.000
6274     103.000
6802      29.440
6635      86.000
5186      70.000
3590      45.000
209       80.000
1204      75.970
3073      75.000
2817      55.500
3221      82.000
1340      96.000
762       88.640
4949      48.000
3052      50.000
4075      30.000
2277      65.000
7059      75.000
2768     170.000
6535      38.000
2776     145.000
4985      60.000
1002      70.0

In [20]:
# now we will find root mean square value

from sklearn.metrics import mean_squared_error
import numpy as np

mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print("MSE : ",mse)
print("RMSE : ",rmse)

MSE :  4093.4831852475745
RMSE :  63.9803343633618
