# Business Problem - Predict the Priceof Banglore House
using Linear Regresssion - Supervised Machine Learning Algorithm

In [102]:
import pandas as pd

In [103]:
#ignore warnings
import warnings
warnings.filterwarnings("ignore")

# show all rows and all columns
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

# data preprocessing
cleaning the data

In [108]:
banglore_df = pd.read_csv(r"C:\Users\user\Pictures\PYTHON_PANDAS\banglore.csv")
banglore_df.shape

(13320, 9)

In [109]:
null_var = banglore_df.isnull().sum()/banglore_df.shape[0] *100
null_var

area_type        0.000000
availability     0.000000
location         0.007508
size             0.120120
society         41.306306
total_sqft       0.000000
bath             0.548048
balcony          4.572072
price            0.000000
dtype: float64

In [69]:
drop_columns = null_var[null_var>10].keys()    # more then 10% null columns will be dropped
drop_columns

Index(['society'], dtype='object')

In [70]:
df2_drop_clm = banglore_df.drop(columns = drop_columns)
df2_drop_clm.shape

(13320, 8)

In [71]:
df3_drop_rows = df2_drop_clm.dropna()

In [72]:
df3_drop_rows.isnull().sum()       # data is cleaned

area_type       0
availability    0
location        0
size            0
total_sqft      0
bath            0
balcony         0
price           0
dtype: int64

In [73]:
df3_drop_rows.head()

area_type   availability                  location       size  \
0  Super built-up  Area         19-Dec  Electronic City Phase II      2 BHK   
1            Plot  Area  Ready To Move          Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move               Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move        Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move                  Kothanur      2 BHK   

  total_sqft  bath  balcony   price  
0       1056   2.0      1.0   39.07  
1       2600   5.0      3.0  120.00  
2       1440   2.0      3.0   62.00  
3       1521   3.0      1.0   95.00  
4       1200   2.0      1.0   51.00

# OneHotEncoding
Now change categorical data to numerical data


In [74]:
df = pd.get_dummies(df3_drop_rows)
df.head()

bath  balcony   price  area_type_Built-up  Area  area_type_Carpet  Area  \
0   2.0      1.0   39.07                         0                       0   
1   5.0      3.0  120.00                         0                       0   
2   2.0      3.0   62.00                         1                       0   
3   3.0      1.0   95.00                         0                       0   
4   2.0      1.0   51.00                         0                       0   

   area_type_Plot  Area  area_type_Super built-up  Area  availability_14-Jul  \
0                     0                               1                    0   
1                     1                               0                    0   
2                     0                               0                    0   
3                     0                               1                    0   
4                     0                               1                    0   

   availability_14-Nov  availability_15-Aug  availability_15-Dec  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   availability_15-Jun  availability_16-Dec  availability_16-Jan  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   availability_16-Jul  availability_16-Mar  availability_16-Nov  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   availability_16-Oct  availability_16-Sep  availability_17-Apr  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   availability_17-Aug  availability_17-Dec  availability_17-Feb  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   availability_17-Jan  availability_17-Jul  availability_17-Jun  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   availability_17-Mar  availability_17-May  availability_17-Nov  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   availability_17-Oct  availability_17-Sep  availability_18-Apr  \
0                    0                    0                    0   
1                    0                    0           

In [75]:
df.shape

(12710, 3353)

# Split Data

In [76]:
X = df.drop('price',axis=1)
y = df['price']   # price is a dependent variable

print("Shape of X = ", X.shape)
print("Shape of y = ", y.shape)

Shape of X =  (12710, 3352)
Shape of y =  (12710,)


In [77]:
# now we will split data into train and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=51)
print("Shape of X_train = ", X_train.shape)
print("Shape of y_train = ", y_train.shape)
print("Shape of X_test = ", X_test.shape)
print("Shape of y_test = ", y_test.shape)

Shape of X_train =  (10168, 3352)
Shape of y_train =  (10168,)
Shape of X_test =  (2542, 3352)
Shape of y_test =  (2542,)


# Feature Scaling

In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

# Linear Regression - ML Model Training

In [79]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(X_train,y_train)

LinearRegression()

In [80]:
#till now our model has learnt the coffiecients

lr.coef_                            # all slopes (B1,B2,......,beta n)

array([ 2.46602301e-01,  1.30952428e+00,  2.82860263e+14, ...,
       -1.88962716e+12, -1.33623389e+12, -2.31419734e+12])

In [81]:
lr.intercept_             # intercept value

105.37273294013683

# Predict the Value of Home and Test

In [82]:
X_test[0,:]            # 0th house and all columns

array([-1.31659073, -0.70958388, -0.47533827, ..., -0.0140262 ,
       -0.00991753, -0.01717936])

In [83]:
lr.predict([X_test[1,:]])     # prediction of 1th house

array([3.4229943e+13])

In [84]:
lr.predict(X_test)          # prediction of all houses that are in X_test data

array([-4.56808407e+01,  3.42299430e+13,  5.18777531e+01, ...,
        7.99558781e+01,  7.84324406e+01,  6.47918156e+01])

In [85]:
y_test

11425      17.190
10513      55.000
11971      57.000
578        73.000
6379       33.920
11006     154.000
318        52.000
7259       55.000
13271      46.760
3132       62.170
1400      296.000
9486       95.000
12215     220.000
2365       62.000
2738       54.590
7797      118.000
7313       72.000
8241      178.000
5772      113.000
4901      126.000
1557       33.600
7756      203.000
304       105.000
884        95.000
3461       68.000
1989      139.000
7449       74.000
5121       54.000
6744       60.000
8360       55.000
8145      110.000
4363      140.000
3919       35.000
9012       28.880
9921       65.000
651       150.000
4994       75.000
6456      131.000
4508      125.000
8186       85.000
10125      72.000
2696       67.980
10544     200.000
10707     600.000
9490      365.000
7125       57.230
10454      48.000
12797      63.000
10711     160.000
3896       74.000
11104      33.500
7180      107.000
13259      69.500
8897       72.900
6644       82.000
546       

In [86]:
lr.score(X_test, y_test)

-7.113409181541133e+26

# Implement Ridge and Lasso Rigression

In [87]:
from sklearn.linear_model import Ridge, Lasso

In [88]:
rd = Ridge()

rd.fit(X_train,y_train)

rd.score(X_test,y_test)

0.525048698683828

In [89]:
ls = Lasso()

ls.fit(X_train,y_train)

ls.score(X_test,y_test)

0.5574008835208938

In [90]:
ls2 = Lasso(alpha=0.5)

ls2.fit(X_train,y_train)

ls2.score(X_test,y_test)

0.5471377092307896

In [91]:
rd2 = Ridge(alpha=2)

rd2.fit(X_train,y_train)

rd2.score(X_test,y_test)

0.5252133678535299

# Model Evaluation

# 1) Root Mean Square Error

In [92]:
y_pred = lr.predict(X_test)
y_pred

array([-4.56808407e+01,  3.42299430e+13,  5.18777531e+01, ...,
        7.99558781e+01,  7.84324406e+01,  6.47918156e+01])

In [93]:
y_test

11425      17.190
10513      55.000
11971      57.000
578        73.000
6379       33.920
11006     154.000
318        52.000
7259       55.000
13271      46.760
3132       62.170
1400      296.000
9486       95.000
12215     220.000
2365       62.000
2738       54.590
7797      118.000
7313       72.000
8241      178.000
5772      113.000
4901      126.000
1557       33.600
7756      203.000
304       105.000
884        95.000
3461       68.000
1989      139.000
7449       74.000
5121       54.000
6744       60.000
8360       55.000
8145      110.000
4363      140.000
3919       35.000
9012       28.880
9921       65.000
651       150.000
4994       75.000
6456      131.000
4508      125.000
8186       85.000
10125      72.000
2696       67.980
10544     200.000
10707     600.000
9490      365.000
7125       57.230
10454      48.000
12797      63.000
10711     160.000
3896       74.000
11104      33.500
7180      107.000
13259      69.500
8897       72.900
6644       82.000
546       

In [96]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [97]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print("MSE : ",mse)
print("RMSE : ",rmse)

MSE :  1.2607448649568461e+31
RMSE :  3550696924487988.5


# R-Square

In [99]:
from sklearn.metrics import r2_score


In [101]:
r2_score(y_test,y_pred)

-7.113409181541133e+26