In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
tips_df = pd.read_csv(r"C:\Users\user\Pictures\PYTHON_PANDAS\tips.csv")
tips_df

total_bill    tip     sex smoker   day    time  size
0         16.99   1.01  Female     No   Sun  Dinner     2
1         10.34   1.66    Male     No   Sun  Dinner     3
2         21.01   3.50    Male     No   Sun  Dinner     3
3         23.68   3.31    Male     No   Sun  Dinner     2
4         24.59   3.61  Female     No   Sun  Dinner     4
5         25.29   4.71    Male     No   Sun  Dinner     4
6          8.77   2.00    Male     No   Sun  Dinner     2
7         26.88   3.12    Male     No   Sun  Dinner     4
8         15.04   1.96    Male     No   Sun  Dinner     2
9         14.78   3.23    Male     No   Sun  Dinner     2
10        10.27   1.71    Male     No   Sun  Dinner     2
11        35.26   5.00  Female     No   Sun  Dinner     4
12        15.42   1.57    Male     No   Sun  Dinner     2
13        18.43   3.00    Male     No   Sun  Dinner     4
14        14.83   3.02  Female     No   Sun  Dinner     2
15        21.58   3.92    Male     No   Sun  Dinner     2
16        10.33   1.67  Female     No   Sun  Dinner     3
17        16.29   3.71    Male     No   Sun  Dinner     3
18        16.97   3.50  Female     No   Sun  Dinner     3
19        20.65   3.35    Male     No   Sat  Dinner     3
20        17.92   4.08    Male     No   Sat  Dinner     2
21        20.29   2.75  Female     No   Sat  Dinner     2
22        15.77   2.23  Female     No   Sat  Dinner     2
23        39.42   7.58    Male     No   Sat  Dinner     4
24        19.82   3.18    Male     No   Sat  Dinner     2
25        17.81   2.34    Male     No   Sat  Dinner     4
26        13.37   2.00    Male     No   Sat  Dinner     2
27        12.69   2.00    Male     No   Sat  Dinner     2
28        21.70   4.30    Male     No   Sat  Dinner     2
29        19.65   3.00  Female     No   Sat  Dinner     2
30         9.55   1.45    Male     No   Sat  Dinner     2
31        18.35   2.50    Male     No   Sat  Dinner     4
32        15.06   3.00  Female     No   Sat  Dinner     2
33        20.69   2.45  Female     No   Sat  Dinner     4
34        17.78   3.27    Male     No   Sat  Dinner     2
35        24.06   3.60    Male     No   Sat  Dinner     3
36        16.31   2.00    Male     No   Sat  Dinner     3
37        16.93   3.07  Female     No   Sat  Dinner     3
38        18.69   2.31    Male     No   Sat  Dinner     3
39        31.27   5.00    Male     No   Sat  Dinner     3
40        16.04   2.24    Male     No   Sat  Dinner     3
41        17.46   2.54    Male     No   Sun  Dinner     2
42        13.94   3.06    Male     No   Sun  Dinner     2
43         9.68   1.32    Male     No   Sun  Dinner     2
44        30.40   5.60    Male     No   Sun  Dinner     4
45        18.29   3.00    Male     No   Sun  Dinner     2
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
48        28.55   2.05    Male     No   Sun  Dinner     3
49        18.04   3.00    Male     No   Sun  Dinner     2
50        12.54   2.50    Male     No   Sun  Dinner     2
51        10.29   2.60  Female     No   Sun  Dinner     2
52        34.81   5.20  Female     No   Sun  Dinner     4
53         9.94   1.56    Male     No   Sun  Dinner     2
54        25.56   4.34    Male     No   Sun  Dinner     4
55        19.49   3.51    Male     No   Sun  Dinner     2
56        38.01   3.00    Male    Yes   Sat  Dinner     4
57        26.41   1.50  Female     No   Sat  Dinner     2
58        11.24   1.76    Male    Yes   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
60        20.29   3.21    Male    Yes   Sat  Dinner     2
61        13.81   2.00    Male    Yes   Sat  Dinner     2
62        11.02   1.98    Male    Yes   Sat  Dinner     2
63        18.29   3.76    Male    Yes   Sat  Dinner     4
64        17.59   2.64    Male     No   Sat  Dinner     3
65        20.08   3.15    Male     No   Sat  Dinner     3
66        16.45   2.47  Female     No   Sat  Dinner     2
67         3.07   1.00  Female    Yes   Sat  Dinner     1
68 

In [9]:
# show all rows and all columns
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [13]:
null_var = tips_df.isnull().sum() / tips_df.shape[0]*100
null_var

total_bill    0.0
tip           0.0
sex           0.0
smoker        0.0
day           0.0
time          0.0
size          0.0
dtype: float64

In [14]:
tips_df.isnull().sum().sum()

0

In [16]:
df = pd.get_dummies(tips_df)
df

total_bill    tip  size  sex_Female  sex_Male  smoker_No  smoker_Yes  \
0         16.99   1.01     2           1         0          1           0   
1         10.34   1.66     3           0         1          1           0   
2         21.01   3.50     3           0         1          1           0   
3         23.68   3.31     2           0         1          1           0   
4         24.59   3.61     4           1         0          1           0   
5         25.29   4.71     4           0         1          1           0   
6          8.77   2.00     2           0         1          1           0   
7         26.88   3.12     4           0         1          1           0   
8         15.04   1.96     2           0         1          1           0   
9         14.78   3.23     2           0         1          1           0   
10        10.27   1.71     2           0         1          1           0   
11        35.26   5.00     4           1         0          1           0   
12        15.42   1.57     2           0         1          1           0   
13        18.43   3.00     4           0         1          1           0   
14        14.83   3.02     2           1         0          1           0   
15        21.58   3.92     2           0         1          1           0   
16        10.33   1.67     3           1         0          1           0   
17        16.29   3.71     3           0         1          1           0   
18        16.97   3.50     3           1         0          1           0   
19        20.65   3.35     3           0         1          1           0   
20        17.92   4.08     2           0         1          1           0   
21        20.29   2.75     2           1         0          1           0   
22        15.77   2.23     2           1         0          1           0   
23        39.42   7.58     4           0         1          1           0   
24        19.82   3.18     2           0         1          1           0   
25        17.81   2.34     4           0         1          1           0   
26        13.37   2.00     2           0         1          1           0   
27        12.69   2.00     2           0         1          1           0   
28        21.70   4.30     2           0         1          1           0   
29        19.65   3.00     2           1         0          1           0   
30         9.55   1.45     2           0         1          1           0   
31        18.35   2.50     4           0         1          1           0   
32        15.06   3.00     2           1         0          1           0   
33        20.69   2.45     4           1         0          1           0   
34        17.78   3.27     2           0         1          1           0   
35        24.06   3.60     3           0         1          1           0   
36        16.31   2.00     3           0         1          1           0   
37        16.93   3.07     3           1         0          1           0   
38        18.69   2.31     3           0         1          1           0   
39        31.27   5.00     3           0         1          1           0   
40        16.04   2.24     3           0         1          1           0   
41        17.46   2.54     2           0         1          1           0   
42        13.94   3.06     2           0         1          1           0   
43         9.68   1.32     2           0         1          1           0   
44        30.40   5.60     4           0         1          1           0   
45        18.29   3.00     2           0         1          1           0   
46        22.23   5.00     2           0         1          1           0   
47        32.40   6.00     4           0         1          1           0   
48        28.55   2.05     3           0         1          1           0   
49        18.04   3.00     2           0         1          1           0   
50        12.54   2.50     2           0         1          1           0   
5

In [17]:
X = df.drop('total_bill',axis=1)
y = df['total_bill']   # price is a dependent variable

print("Shape of X = ", X.shape)
print("Shape of y = ", y.shape)

Shape of X =  (244, 12)
Shape of y =  (244,)


# Split Data

In [18]:
# now we will split data into train and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=51)
print("Shape of X_train = ", X_train.shape)
print("Shape of y_train = ", y_train.shape)
print("Shape of X_test = ", X_test.shape)
print("Shape of y_test = ", y_test.shape)

Shape of X_train =  (195, 12)
Shape of y_train =  (195,)
Shape of X_test =  (49, 12)
Shape of y_test =  (49,)


# Feature Scaling

In [19]:

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

# Linear Regression - ML Model

In [20]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr.fit(X_train,y_train)

LinearRegression()

In [21]:
#till now our model has learnt the coffiecients

lr.coef_                            # all slopes (B1,B2,......,beta n)

array([ 4.03652746,  3.11998685, -0.25300725,  0.25300725, -0.65461348,
        0.65461348, -0.28024447, -0.27581191, -0.48938912,  0.9751546 ,
        0.94882385, -0.94882385])

In [22]:
lr.intercept_             # intercept value

19.567384615384615

In [23]:
lr.predict(X_test)          # prediction of all houses that are in X_test data

array([26.93461656, 15.35612321, 16.42873609, 37.95086131, 22.71920745,
       20.82484109, 15.39051602, 17.19430852, 17.64495489, 19.85774667,
       16.03830985, 16.37629309, 10.14754869, 32.07632866, 12.3954942 ,
       36.20771337, 18.83904813, 16.00866651, 16.31077177, 10.73940513,
       13.31011012, 20.5799215 , 24.47186153, 16.19967177, 13.56571218,
       16.86162647, 23.5711273 , 21.36425453, 16.96974815, 15.82657029,
       19.90702578, 16.86162647, 10.73940513, 42.22649055, 24.05132522,
       11.2813863 , 14.83293814, 19.82864121, 17.37496891, 12.71219156,
       19.86178573, 29.12714091, 16.60943198, 15.85714708, 20.41461414,
       14.68385915, 21.96645583, 17.90159704, 24.88612753])

In [24]:
y_test

39     31.27
190    15.69
203    16.40
23     39.42
35     24.06
171    15.81
97     12.03
45     18.29
115    17.31
71     17.07
193    15.48
162    16.21
0      16.99
142    41.19
235    10.07
156    48.17
232    11.61
134    18.26
89     21.16
132    11.17
10     10.27
210    30.06
4      24.59
14     14.83
146    18.64
177    14.48
186    20.90
65     20.08
209    12.76
217    11.59
90     28.97
176    17.89
145     8.35
212    48.33
7      26.88
121    13.42
237    32.83
64     17.59
42     13.94
99     12.46
104    20.92
63     18.29
58     11.24
21     20.29
173    31.85
68     20.23
19     20.65
36     16.31
238    35.83
Name: total_bill, dtype: float64

In [25]:
lr.score(X_test, y_test)

0.6531895194803714

# Implementing Ridge and Lasso Regression

In [26]:
from sklearn.linear_model import Ridge, Lasso

In [28]:
rd = Ridge()

rd.fit(X_train,y_train)

rd.score(X_test,y_test)

0.6524754634197769

In [29]:
ls = Lasso()

ls.fit(X_train,y_train)

ls.score(X_test,y_test)

0.6013889779540107

In [34]:
rd2 = Ridge(alpha=0.5)

rd2.fit(X_train,y_train)

rd2.score(X_test,y_test)

0.6528323733439898

In [36]:
ls2 = Lasso(alpha=0.5)

ls2.fit(X_train,y_train)

ls2.score(X_test,y_test)

0.6322925784906905

# Model Evaluation

# 1) Root Mean Square Error

In [37]:
y_pred = lr.predict(X_test)
y_pred

array([26.93461656, 15.35612321, 16.42873609, 37.95086131, 22.71920745,
       20.82484109, 15.39051602, 17.19430852, 17.64495489, 19.85774667,
       16.03830985, 16.37629309, 10.14754869, 32.07632866, 12.3954942 ,
       36.20771337, 18.83904813, 16.00866651, 16.31077177, 10.73940513,
       13.31011012, 20.5799215 , 24.47186153, 16.19967177, 13.56571218,
       16.86162647, 23.5711273 , 21.36425453, 16.96974815, 15.82657029,
       19.90702578, 16.86162647, 10.73940513, 42.22649055, 24.05132522,
       11.2813863 , 14.83293814, 19.82864121, 17.37496891, 12.71219156,
       19.86178573, 29.12714091, 16.60943198, 15.85714708, 20.41461414,
       14.68385915, 21.96645583, 17.90159704, 24.88612753])

In [38]:
y_test

39     31.27
190    15.69
203    16.40
23     39.42
35     24.06
171    15.81
97     12.03
45     18.29
115    17.31
71     17.07
193    15.48
162    16.21
0      16.99
142    41.19
235    10.07
156    48.17
232    11.61
134    18.26
89     21.16
132    11.17
10     10.27
210    30.06
4      24.59
14     14.83
146    18.64
177    14.48
186    20.90
65     20.08
209    12.76
217    11.59
90     28.97
176    17.89
145     8.35
212    48.33
7      26.88
121    13.42
237    32.83
64     17.59
42     13.94
99     12.46
104    20.92
63     18.29
58     11.24
21     20.29
173    31.85
68     20.23
19     20.65
36     16.31
238    35.83
Name: total_bill, dtype: float64

In [39]:
from sklearn.metrics import mean_squared_error
import numpy as np

In [40]:
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)
print("MSE : ",mse)
print("RMSE : ",rmse)

MSE :  31.36992665688554
RMSE :  5.600886238523823


# R-Square

In [41]:
from sklearn.metrics import r2_score


In [42]:
r2_score(y_test,y_pred)

0.6531895194803714