# Random Forest Classification

In [21]:
import numpy as np
import pandas as pd

In [22]:
#ignore warnings
import warnings
warnings.filterwarnings("ignore")

# show all rows and all columns
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [23]:
# load dataset
from sklearn.datasets import load_breast_cancer
data =  load_breast_cancer()

In [24]:
data.data          # in dictionary format

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [25]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [26]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [27]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

In [28]:
# create dataframe
df = pd.DataFrame(np.c_[data.data,data.target],columns = [list(data.feature_names)+['target']])
df.head()

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760         0.3001             0.14710        0.2419   
1          0.07864         0.0869             0.07017        0.1812   
2          0.15990         0.1974             0.12790        0.2069   
3          0.28390         0.2414             0.10520        0.2597   
4          0.13280         0.1980             0.10430        0.1809   

  mean fractal dimension radius error texture error perimeter error  \
0                0.07871       1.0950        0.9053           8.589   
1                0.05667       0.5435        0.7339           3.398   
2                0.05999       0.7456        0.7869           4.585   
3                0.09744       0.4956        1.1560           3.445   
4                0.05883       0.7572        0.7813           5.438   

  area error smoothness error compactness error concavity error  \
0     153.40         0.006399           0.04904         0.05373   
1      74.08         0.005225           0.01308         0.01860   
2      94.03         0.006150           0.04006         0.03832   
3      27.23         0.009110           0.07458         0.05661   
4      94.44         0.011490           0.02461         0.05688   

  concave points error symmetry error fractal dimension error worst radius  \
0              0.01587        0.03003                0.006193        25.38   
1              0.01340        0.01389                0.003532        24.99   
2              0.02058        0.02250                0.004571        23.57   
3              0.01867        0.05963                0.009208        14.91   
4              0.01885        0.01756                0.005115        22.54   

  worst texture worst perimeter worst area worst smoothness worst compactness  \
0         17.33          184.60     2019.0           0.1622            0.6656   
1         23.41          158.80     1956.0           0.1238            0.1866   
2         25.53          152.50     1709.0           0.1444            0.4245   
3         26.50           98.87      567.7           0.2098            0.8663   
4         16.67          152.20     1575.0           0.1374            0.2050   

  worst concavity worst concave points worst symmetry worst fractal dimension  \
0          0.7119               0.2654         0.4601                 0.11890   
1          0.2416               0.1860         0.2750                 0.08902   
2          0.4504               0.2430         0.3613                 0.08758   
3          0.6869               0.2575         0.6638                 0.17300   
4          0.4000               0.1625         0.2364                 0.07678   

  target  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0

In [29]:
df.tail()

mean radius mean texture mean perimeter mean area mean smoothness  \
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension radius error texture error perimeter error  \
564                0.05623       1.1760         1.256           7.673   
565                0.05533       0.7655         2.463           5.203   
566                0.05648       0.4564         1.075           3.425   
567                0.07016       0.7260         1.595           5.772   
568                0.05884       0.3857         1.428           2.548   

    area error smoothness error compactness error concavity error  \
564     158.70         0.010300           0.02891         0.05198   
565      99.04         0.005769           0.02423         0.03950   
566      48.55         0.005903           0.03731         0.04730   
567      86.22         0.006522           0.06158         0.07117   
568      19.15         0.007189           0.00466         0.00000   

    concave points error symmetry error fractal dimension error worst radius  \
564              0.02454        0.01114                0.004239       25.450   
565              0.01678        0.01898                0.002498       23.690   
566              0.01557        0.01318                0.003892       18.980   
567              0.01664        0.02324                0.006185       25.740   
568              0.00000        0.02676                0.002783        9.456   

    worst texture worst perimeter worst area worst smoothness  \
564         26.40          166.10     2027.0          0.14100   
565         38.25          155.00     1731.0          0.11660   
566         34.12          126.70     1124.0          0.11390   
567         39.42          184.60     1821.0          0.16500   
568         30.37           59.16      268.6          0.08996   

    worst compactness worst concavity worst concave points worst symmetry  \
564           0.21130          0.4107               0.2216         0.2060   
565           0.19220          0.3215               0.1628         0.2572   
566           0.30940          0.3403               0.1418         0.2218   
567           0.86810          0.9387               0.2650         0.4087   
568           0.06444          0.0000               0.0000         0.2871   

    worst fractal dimension target  
564                 0.07115    0.0  
565                 0.06637    0.0  
566                 0.07820    0.0  
567                 0.12400    0.0  
568                 0.07039    1.0

In [30]:
df.shape

(569, 31)

# Split Data

In [31]:
X = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

In [32]:
X.shape,y.shape

((569, 30), (569,))

In [33]:
# now we will split data into train and test data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=51)
print("Shape of X_train = ", X_train.shape)
print("Shape of y_train = ", y_train.shape)
print("Shape of X_test = ", X_test.shape)
print("Shape of y_test = ", y_test.shape)

Shape of X_train =  (455, 30)
Shape of y_train =  (455,)
Shape of X_test =  (114, 30)
Shape of y_test =  (114,)


# Train Random Forest Classification Model

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
classifier = RandomForestClassifier(n_estimators=100, criterion='gini',)
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [36]:
classifier.score(X_test,y_test)

0.9385964912280702

# Predict Cancer

In [37]:
patient1 = [17.99,
 10.38,
 122.8,
 1001.0,
 0.1184,
 0.2776,
 0.3001,
 0.1471,
 0.2419,
 0.07871,
 1.095,
 0.9053,
 8.589,
 153.4,
 0.006399,
 0.04904,
 0.05373,
 0.01587,
 0.03003,
 0.006193,
 25.38,
 17.33,
 184.6,
 2019.0,
 0.1622,
 0.6656,
 0.7119,
 0.2654,
 0.4601,
 0.1189]

In [38]:
patient1 = np.array([patient1])       # convert it into two dimension numpy array
patient1

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]])

In [39]:
pred = classifier.predict(patient1)
pred

array([0.])

In [40]:
if pred[0] ==0 :
    print('Patient has cancer (malignant tumor)')
else :
    print('Patient has no cancer (malignant benign)')

Patient has cancer (malignant tumor)


# Save Model

In [41]:
import pickle

In [42]:
pickle.dump(classifier, open("model_save","wb"))       # now our classifier saved into model_Save file

In [43]:
model = pickle.load(open("model_save","rb"))

In [44]:
model.predict(patient1)

array([0.])

In [45]:
# use another library for save the model

In [46]:
import joblib

In [47]:
joblib.dump(classifier,"model_save2")

['model_save2']

In [48]:
model2 = joblib.load("model_save2")

In [49]:
model2.predict(patient1)

array([0.])